"use client";

import { useMemo } from "react";
import { Badge } from "@/components/ui/badge";
import type { PatternCluster } from "@/types/api";

interface ScheduleMeetingProps {
  findings: PatternCluster[];
  onBack: () => void;
  onSend: () => void;
}

export function ScheduleMeeting({
  findings,
  onBack,
  onSend,
}: ScheduleMeetingProps) {
  const agendaText = useMemo(() => {
    const lines = [
      "## Alignment Meeting Agenda\n",
      "### Feedback Analysis Review\n",
    ];
    for (let i = 0; i < findings.length; i++) {
      const finding = findings[i];
      lines.push(
        `${i + 1}. **${finding.pain_summary || finding.label}**`,
      );
      lines.push(
        `   - ${finding.frequency} mentions, ${finding.evidence_quotes.length} evidence points\n`,
      );
    }
    lines.push("### Discussion Points");
    lines.push("- Prioritization and sequencing");
    lines.push("- Resource allocation");
    lines.push("- Timeline and milestones\n");
    lines.push("---\nGenerated by Napkin");
    return lines.join("\n");
  }, [findings]);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(agendaText);
    onSend();
  };

  return (
    <div>
      <button
        type="button"
        onClick={onBack}
        className="flex items-center gap-1 text-sm text-muted hover:text-foreground transition-colors mb-4"
      >
        &larr; Back
      </button>

      <Badge variant="default" className="mb-4">
        Meeting Agenda
      </Badge>

      <div className="bg-surface border border-border rounded-xl p-5">
        <pre className="text-sm text-foreground whitespace-pre-wrap font-sans leading-relaxed">
          {agendaText}
        </pre>
      </div>

      <div className="flex justify-end mt-6">
        <button
          type="button"
          onClick={handleCopy}
          className="flex items-center gap-2 px-6 py-3 rounded-xl text-sm font-medium text-white transition-colors"
          style={{ backgroundColor: "var(--accent-action)" }}
          onMouseOver={(e) =>
            (e.currentTarget.style.backgroundColor =
              "var(--accent-action-hover)")
          }
          onMouseOut={(e) =>
            (e.currentTarget.style.backgroundColor = "var(--accent-action)")
          }
        >
          Copy agenda
        </button>
      </div>
    </div>
  );
}
