"use client";

import { useMemo } from "react";
import { Badge } from "@/components/ui/badge";
import type { PatternCluster } from "@/types/api";

interface ShareWithProductProps {
  findings: PatternCluster[];
  onBack: () => void;
  onSend: () => void;
}

export function ShareWithProduct({
  findings,
  onBack,
  onSend,
}: ShareWithProductProps) {
  const summaryText = useMemo(() => {
    const lines = [
      "## Feedback Analysis Summary\n",
      `Napkin analyzed feedback and found ${findings.length} key pattern${findings.length !== 1 ? "s" : ""}:\n`,
    ];
    for (const finding of findings) {
      const severity =
        finding.severity_score >= 0.7
          ? "CRITICAL"
          : finding.severity_score >= 0.4
            ? "OPPORTUNITY"
            : "INSIGHT";
      lines.push(`### [${severity}] ${finding.pain_summary || finding.label}`);
      lines.push(`- Frequency: ${finding.frequency} mentions`);
      lines.push(
        `- Evidence: ${finding.evidence_quotes.length} data points`,
      );
      lines.push(
        `- Confidence: ${Math.round(finding.confidence * 100)}%\n`,
      );
    }
    lines.push("\n---\nGenerated by Napkin");
    return lines.join("\n");
  }, [findings]);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(summaryText);
    onSend();
  };

  return (
    <div>
      <button
        type="button"
        onClick={onBack}
        className="flex items-center gap-1 text-sm text-muted hover:text-foreground transition-colors mb-4"
      >
        &larr; Back
      </button>

      <Badge variant="default" className="mb-4">
        Product Team
      </Badge>

      <div className="bg-surface border border-border rounded-xl p-5">
        <pre className="text-sm text-foreground whitespace-pre-wrap font-sans leading-relaxed">
          {summaryText}
        </pre>
      </div>

      <div className="flex justify-end mt-6">
        <button
          type="button"
          onClick={handleCopy}
          className="flex items-center gap-2 px-6 py-3 rounded-xl text-sm font-medium text-white transition-colors"
          style={{ backgroundColor: "var(--accent-action)" }}
          onMouseOver={(e) =>
            (e.currentTarget.style.backgroundColor =
              "var(--accent-action-hover)")
          }
          onMouseOut={(e) =>
            (e.currentTarget.style.backgroundColor = "var(--accent-action)")
          }
        >
          Copy summary
        </button>
      </div>
    </div>
  );
}
